// Generated by gencpp from file my_complex_pkg/Complex.msg
// DO NOT EDIT!


#ifndef MY_COMPLEX_PKG_MESSAGE_COMPLEX_H
#define MY_COMPLEX_PKG_MESSAGE_COMPLEX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_complex_pkg
{
template <class ContainerAllocator>
struct Complex_
{
  typedef Complex_<ContainerAllocator> Type;

  Complex_()
    : re(0.0)
    , im(0.0)  {
    }
  Complex_(const ContainerAllocator& _alloc)
    : re(0.0)
    , im(0.0)  {
  (void)_alloc;
    }



   typedef float _re_type;
  _re_type re;

   typedef float _im_type;
  _im_type im;





  typedef boost::shared_ptr< ::my_complex_pkg::Complex_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_complex_pkg::Complex_<ContainerAllocator> const> ConstPtr;

}; // struct Complex_

typedef ::my_complex_pkg::Complex_<std::allocator<void> > Complex;

typedef boost::shared_ptr< ::my_complex_pkg::Complex > ComplexPtr;
typedef boost::shared_ptr< ::my_complex_pkg::Complex const> ComplexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_complex_pkg::Complex_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_complex_pkg::Complex_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_complex_pkg::Complex_<ContainerAllocator1> & lhs, const ::my_complex_pkg::Complex_<ContainerAllocator2> & rhs)
{
  return lhs.re == rhs.re &&
    lhs.im == rhs.im;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_complex_pkg::Complex_<ContainerAllocator1> & lhs, const ::my_complex_pkg::Complex_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_complex_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_complex_pkg::Complex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_complex_pkg::Complex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_complex_pkg::Complex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_complex_pkg::Complex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_complex_pkg::Complex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_complex_pkg::Complex_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_complex_pkg::Complex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "912f775e9b7f1ccab5a7496314643393";
  }

  static const char* value(const ::my_complex_pkg::Complex_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x912f775e9b7f1ccaULL;
  static const uint64_t static_value2 = 0xb5a7496314643393ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_complex_pkg::Complex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_complex_pkg/Complex";
  }

  static const char* value(const ::my_complex_pkg::Complex_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_complex_pkg::Complex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 re\n"
"float32 im\n"
;
  }

  static const char* value(const ::my_complex_pkg::Complex_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_complex_pkg::Complex_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.re);
      stream.next(m.im);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Complex_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_complex_pkg::Complex_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_complex_pkg::Complex_<ContainerAllocator>& v)
  {
    s << indent << "re: ";
    Printer<float>::stream(s, indent + "  ", v.re);
    s << indent << "im: ";
    Printer<float>::stream(s, indent + "  ", v.im);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_COMPLEX_PKG_MESSAGE_COMPLEX_H
